# Generated by Django 4.2.3 on 2023-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_balancereport_cash_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereport',
            name='cash_in',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='cash_out',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='payable',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='receivable',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
