# Generated by Django 4.2.3 on 2023-07-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_balancereport_cash_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='cash_in',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='cash_out',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
